authors/urls.py
from django.urls import path, include
from core import views
from django.contrib.auth.views import auth_login
from django.contrib.auth import views as auth_views
from accounts import views

app_name='panel'

urlpatterns = [
    path('acessar/',  auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', auth_views.LogoutView.as_view(next_page='core:home') , name='logout'),
    path('registrar/', views.register, name='register'),
    path('editar/', views.edit_user, name='edituser'),
    path('editar_senha/', views.edit_password, name='editpassword'),
    path('resetar_senha/', views.password_reset, name='passwordreset'),
    path('confirmar_senha/(<str:key>\w+)/', views.password_reset_confirm, name='passwordconfirm'),
    path('dashboard/',  views.dashboard, name='dashboard'),
]

core/urls.py
from django.urls import path, include
from core import views

app_name='core'

urlpatterns = [
    path('galeria/', views.gallery, name='gallery'),
    path('acervo/', views.lib, name='lib'),
    path('', views.home, name='home'),
    path('about', views.about, name='about')
]

letraspotengienses/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf import settings
#from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('painel/', include('accounts.urls', namespace='panel')),
    path('author/', include('authors.urls', namespace='authors')),
]

accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.conf import settings
from django.utils.translation import gettext_lazy as _

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('E-mail', unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), 'O e-mail não pode conter espaços', 'invalid')])
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É administrador?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Cadastro', auto_now_add=True)
    date_updated =models.DateTimeField('Atualizado em', auto_now=True) 
    
    class Occupation(models.TextChoices):
        STUDENT = 'Estudante', _('Estudante')
        PROFESSIONAL = 'Profissional', _('Profissional')
        OTHER = 'Outro', _('Outro')
    
    ocucupation = models.CharField('Ocupação',
        max_length=12,
        choices=Occupation.choices,
        default=Occupation.STUDENT,    
        blank=False)
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'ocucupation']

    def __str__(self):
        return self.name or self.email
    
    def get_short_name(self):
        return self.name

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name:'Usuário'
        verbose_name_plural:'Usuários'

class PasswordReset(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.PROTECT, related_name='resets')
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name='Nova Senha'
        verbose_name_plural='Novas Senhas'
        ordering = ['-created_at']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, get_user_model
from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from django.contrib.auth.decorators import login_required
from core.utils import generate_hash_key
from django.conf import settings
#from titles.models import Enrollment


User = get_user_model()

from  .models import PasswordReset
# Create your views here.
def register(request):
    template_name='register.html'
    
    if request.method == 'POST':
        form = RegisterForm(request.POST) 
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
        else:
           pass
    else:
        form = RegisterForm()
    
    context={
        'form': form
    }
    return render(request, template_name, context)

@login_required
def dashboard(request):
    template_name='dashboard.html'
    context = {}
    context['form'] = EditAccountForm()
    #context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)

@login_required
def edit_user(request):
    template_name='edituser.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
        else:
            pass   
    else:
        form = EditAccountForm(instance=request.user)
    
    context['form'] = form

    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name='editpassword.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
        else:
            pass   
    else:
        form = PasswordChangeForm(user=request.user)
    
    context['form'] = form

    return render(request, template_name, context)

def password_reset(request):
    template_name="password_reset.html"
    form = PasswordResetForm(request.POST or None)
    context = {}
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    template_name = 'password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key = key)
    form = SetPasswordForm(user = reset.user, data = request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

accounts/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
       #mainNav{
           background-color: #212529 !important;
       }
       #a-login {
           background-color: #FFBE00 !important;
           color:black;
       }

        body{
            background:black;
        }
    </style>
    <!-- Heading Row-->
     <header id="login" class="heading">
         <div class="container">
            <div class="row">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">
                     {% block dashboard_tite %}
                            Painel de Controle
                    {% endblock %}
                    </h2>
                    <ul id="user-menu">
                        <li><a id="a-painel" href="{% url 'panel:dashboard' %}">Painel</a></li>
                        <li><a id="a-senha" href="{% url 'panel:editpassword' %}">Editar Senha</a></li>
                        <li><a id="a-conta" href="{% url 'panel:edituser' %}">Editar Conta</a></li>
                        <li><a href="{% url 'panel:logout' %}">Sair</a></li>
                    </ul>
                </div>
            </div>
    </header>
    
    <section class="page-section bg-light h-100">
        <div class="container">
            <div class="pure-g-r content-ribbon">
            {% if messages %}
            <aside class="pure-u-1 msg">
                {% for message in messages %}
                    <p>{{message}}</p>
                {% endfor %}
            </aside>
            {% endif %}
            <div class="pure-u-1-3">
                <div class='pure-menu pure-menu-open sm-paddding'>
                   
                </div>
            </div>    
            <div class="pure-u-2-3">
                <div class="inner sm-paddding">
                    {% block dashboard_content %}Em manutenção{% endblock %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/editpassword.html
{% extends "dashboard.html" %}
{% block dashboard_tite %}
    Editar Senha
{% endblock %}

{% block dashboard_content %}
    <style>
        #user-menu #a-senha{
            color: rgb(252, 122, 0);
        }
    </style>
    <form class="pure-form pure-form-aligned" method="POST">
        {% csrf_token %}
        {% if success %}
            <div class="success"> A senha foi alterada com sucesso </div>
        {% endif %}
        <fieldset>   
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field}}
                {{ field.errors }}
            </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Salvar</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/edituser.html
{% extends "dashboard.html" %}
{% block dashboard_tite %}
    Editar Conta
{% endblock %}

{% block dashboard_content %}
    <style>
        #user-menu #a-conta{
            color: rgb(252, 122, 0);
        }
    </style>
    <form class="pure-form pure-form-aligned" method="POST">
        {% csrf_token %}
        {% if success %}
            <div class="success"> Os dados foram alterados com sucesso </div>
        {% endif %}
        <fieldset>
           
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field}}
                {{ field.errors }}
            </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Salvar</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
       #mainNav{
           background-color: #212529 !important;
       }
       #a-login {
           background-color: #FFBE00 !important;
           color:black;
       }

        body{
            background:black;
        }
    </style>
    <!-- Heading Row-->
     <header id="login" class="heading">
         <div class="container">
            <div class="row">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Acessar o sistema</h2>
                </div>
            </div>
    </header>
    
    <section class="page-section bg-light h-100" id="login">
        <div class="container">
         <div class="row">
            <div class="col-sm-5 col-md-6 mb-3 p-45 form-wrap ">
                <div class="pure-g-r content-ribbon bg-login p-4">
                    
                    <div class="pure-u-1">
                        
                        <form class="pure-form pure-form-aligned" method="POST">
                            {% csrf_token %}
                            <fieldset>
                             {{ form.non_field_errors }}
                            {% for field in form %}
                            <div class="pure-control-group">
                                {{ field.label_tag }}
                                {{ field}}
                                {{ field.errors }}
                            </div>

                            {% endfor %}
                            <div class="pure-controls">
                                <button type="submit" class="btn btn-lg bg-dark text-white">Entrar</button>
                                <a  href="{% url 'panel:passwordreset' %}" class="btn btn-lg bg-warning text-black">Resetar senha?</a>
                            </div>
                            
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
    </section>
{% endblock %}

accounts/templates/password_reset.html
{% extends "base.html" %}
{% block content %}
    <div class="splash">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Redefinir senha
                    </h1>
                    <h2 class="splash-subhead">
                        Informe seus dados de cadastro
                    </h2>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            {% if success %}
                <div class="success"> Os dados foram enviados ao e-mail informado.</div>
            {% else %}
            <form class="pure-form pure-form-aligned" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="pure-control-group">
                      {{ field.label_tag }}
                      {{ field}}
                      {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar o e-mail</button>
                    </div>
                
                </fieldset>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
    <div class="splash">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Redefinir senha
                    </h1>
                    <h2 class="splash-subhead">
                        Informe sua nova senha
                    </h2>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            {% if success %}
                <div class="success"> Sua nova senha foi criada com sucesso.</div>
            {% else %}
            <form class="pure-form pure-form-aligned" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="pure-control-group">
                      {{ field.label_tag }}
                      {{ field}}
                      {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                
                </fieldset>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/password_reset_email.html
<p>Para criar uma nova senha acessar o link:</p>
<a href="{% url 'panel:passwordconfirm' reset.key %}"> Clique para criar nova senha</a>

accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
       #mainNav{
           background-color: #212529 !important;
       }
       #a-register {
           background-color: #FFBE00 !important;
           color:black;
       }

        body{
            background:black;
        }
    </style>
    <!-- Heading Row-->
     <header id="registro" class="heading">
         <div class="container">
            <div class="row">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Cadastrar-se</h2>
                </div>
            </div>
    </header>
    
    <section class="page-section bg-light h-100" id="registro">
        <div class="container">
            <div class="row">
                <div class="col-10 col-md-9 col-sm-12 mb-3 p-45 form-wrap">
                    <div class="pure-g-r content-ribbon bg-login p-4">
                     {{ form.non_field_errors }}
                        <div class="pure-u-1">
                            <form class="pure-form pure-form-aligned" method="POST">
                            {% csrf_token %}
                            <fieldset>
                            {{ form.non_field_errors }}
                            {% for field in form %}
                            <div class="pure-control-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {{ field.errors }}
                            </div>
                            {% endfor %}
                            <div class="pure-controls">
                                <button type="submit" class="btn btn-lg bg-warning">Cadastrar</button>
                            </div>
                            </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
    </section>
{% endblock %}