authors/urls.py
from django.urls import path, include
from core import views
from django.contrib.auth.views import auth_login
from django.contrib.auth import views as auth_views
from accounts import views

app_name='panel'

urlpatterns = [
    path('acessar/',  auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', auth_views.LogoutView.as_view(next_page='core:home') , name='logout'),
    path('registrar/', views.register, name='register'),
    path('editar/', views.edit_user, name='edituser'),
    path('editar_senha/', views.edit_password, name='editpassword'),
    path('resetar_senha/', views.password_reset, name='passwordreset'),
    path('confirmar_senha/(<str:key>\w+)/', views.password_reset_confirm, name='passwordconfirm'),
    path('dashboard/',  views.dashboard, name='dashboard'),
]

core/urls.py
from django.urls import path, include
from core import views

app_name='core'

urlpatterns = [
    path('galeria/', views.gallery, name='gallery'),
    path('acervo/', views.lib, name='lib'),
    path('', views.home, name='home'),
    path('about', views.about, name='about')
]

letraspotengienses/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf import settings
#from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('painel/', include('accounts.urls', namespace='panel')),
    path('author/', include('authors.urls', namespace='authors')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
   return render(request, 'home.html')

def gallery(request):
    return render(request, 'gallery.html')

def lib(request):
    return render(request, 'acervo.html')

def about(request):
    return render(request, 'about.html')

core/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
       #mainNav{
           background-color: #212529 !important;
       }
       #a-about {
           background-color: #FFBE00 !important;
           color:black;
       }
    </style>
    <!-- Heading Row-->
    <header id="about" class="heading">
         <div class="container">
            <div class="row">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">SOBRE</h2>
                </div>
            </div>
    </header>
    
    <section class="page-section" id="descricao">
        <div class="container">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-top my-5">
                <div class="col-lg-7">
                    <p class="text-wrap text-justify">O projeto de pesquisa Letras Potengienses é uma iniciativa de professores e alunos de Língua Portuguesa do Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte - Campus São Paulo do Potengi -, com o objetivo de empreender um levantamento dos enunciados literários da referida cidade.</p>
                    <p class="text-wrap text-justify">Seu propósito maior é viabilizar o acesso da população às Letras locais, como legado da investigação e da catalogação de sua produção literária, ampliando conhecimentos acerca do município em seu aspecto discursivo e adensando a consciência sobre a existência e a importância de um “acervo literário potengiense”, na sua condição de patrimônio imaterial da cidade.</p>
                    <p class="text-wrap text-justify">Pautado em um diálogo profícuo com os escritores locais, boa parte deles componente da Academia Potengiense de Letras e Artes (APLA), o projeto construiu um inventário das obras regionais por eles produzidas. Ao fim dele, como conquista maior, apresentamos um acervo físico e digital de títulos/obras potengienses, partícipes de um catálogo rico, entregue à sociedade local com admiração e entusiasmo.</p>
                    <p class="text-wrap text-justify">Agradecemos a todos os colaboradores desta pesquisa e desejamos a você, car@ visitante, que explore este acervo e viva a sensível experiência de se encontrar e se encantar com o que têm a dizer as Letras de São Paulo do Potengi.</p>
                    <p class="text-wrap text-justify">Seja bem-vind@!</p>
                </div>
                <div class="col-lg-5">
                    <img id="i-about" class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'assets/img/about.jpg' %}" alt="..." />
                </div>
                
            </div>    
        </div>
    </section>    
    
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center mb-5">
                    <h2 class="section-heading text-uppercase">Equipe</h2>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/1.jpg'%}" alt="..." />
                            <h4>Karen Luiza Cruz Rezende</h4>
                            <p class="text-muted">Aluna</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/2.jpg' %}" alt="..." />
                            <h4>Maria Camily de Alencar Dias</h4>
                            <p class="text-muted">Aluna</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/3.jpg'%}" alt="..." />
                            <h4>Mateus Levy Basílio de Macedo</h4>
                            <p class="text-muted">Aluno</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/4.jpg'%}" alt="..." />
                            <h4>Bruno de Paula Barbosa</h4>
                            <p class="text-muted">Professor de Língua Portuguesa/Inglesa</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/5.jpg'%}" alt="..." />
                            <h4>Fernanda de Moura Ferreira</h4>
                            <p class="text-muted">Professora de Língua Portuguesa e Literatura Brasileira</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/6.jpg'%}" alt="..." />
                            <h4>Tacicleide Dantas Vieira</h4>
                            <p class="text-muted">Coordenadora do projeto</p>
                        </div>
                    </div>
                </div>
               
            </div>
    </section>
    <!-- Parceiros -->
    <section class="page-section" id="parceiros">
         <div class="container">
                <div class="text-center mb-5">
                    <h2 class="section-heading text-uppercase">Realização</h2>
                </div>
                <div class="row align-items-center text-center">
                    <div class="col-md-3 col-sm-6 my-3 mx-auto" >
                        <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="{% static 'assets/img/logos/ifrn.png'%}" alt="..." /></a>
                    </div>
                   
                </div>
            </div>
    </section>
{% endblock %}

core/templates/acervo.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
       #mainNav{
           background-color: #212529 !important;
       }
       #a-lib {
           background-color: #FFBE00 !important;
           color:black;
       }
    </style>
    <!-- Heading Row-->
    <header id="acervo" class="heading">
         <div class="container">
            <div class="row">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">AUTORES</h2>
                </div>
            </div>
    </header>
    
    <section class="page-section" id="acervo">
        <div class="container h-100">
            <ul>
                <li>Alcides Francisco Vilar de Queiroz</li>
<li>Aluísio Azevedo</li>
<li>Aluísio Azevedo Júnior</li>
<li>Auta Pinheiro Bezerra</li>
<li>Brunno Mariano Campos</li>
<li>Cleudia Bezerra Pacheco</li>
<li>Geilton Protásio Bentes</li>
<li>Haroldo Pinheiro Borges</li>
<li>Henriqueta Rosa de Castro Baptista</li>
<li>Hugo Tavares Dutra</li>
<li>Ivo Ferreira Neto</li>
<li>Joanir César</li>
<li>João Guilherme de Souza Filho</li>
<li>José Ferreira da Rocha</li>
<li>Maria Eugênia de Melo Bentes</li>
<li>Maria Gorete Macêdo e Silva</li>
<li>Maria Naldi Gomes Pinheiro</li>
<li>Moacir Farias</li>
<li>Socorro Maciel</li>
            </ul>
        </div>
    </section>
{% endblock %}

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Letras Potengienses" />
    <title>LetrasPotengienses</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.png'%}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
 
     <!-- Template -->
    <link rel="stylesheet" href="{% static 'css/template.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />    
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{% static 'assets/img/logos/logo.png'%}" alt="..." /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars "></i>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a id="a-home" class="nav-link" href="{% url 'core:home' %}">Início</a></li>
                    <li class="nav-item"><a id="a-about" class="nav-link" href="{% url 'core:about' %}">Projeto</a></li>
                    <li class="nav-item"><a id="a-gallery" class="nav-link" href="{% url 'core:gallery' %}">Galeria</a></li>
                    <li class="nav-item"><a id="a-lib" class="nav-link"  href="{% url 'core:lib' %}">Acervo</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a id="a-login" class="nav-link" href="{% url 'panel:dashboard' %}">Painel</a></li>
                        
                    {% else %}
                        <li class="nav-item"><a id="a-login" class="nav-link" href="{% url 'panel:login' %}">Entrar</a></li>
                        <li class="nav-item"><a id="a-register" class="nav-link" href="{% url 'panel:register' %}">Cadastrar-se</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
   
    <div class="content h-80">
        {% block content %}{% endblock %}
    </div>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <span id="copyrights" class="bg-dark">
                    &copy; Letras Potengienses
                  
                </span>
                <div>
                        <a class="btn btn-warning btn-social mx-2" target="blank" href="mailto: letraspotengienses@gmail.com"><i class="fas fa-envelope"></i></a>
                        <a class="btn btn-warning btn-social mx-2" target="blank" href="https://www.instagram.com/letraspotengienses/"><i class="fab fa-instagram"></i></a>
                </div>
               
            </div>
        </div>
    </footer>
    
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>

    <!-- jquery-->
    <script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>

    <!--  Template -->
    <script src="{% static 'js/template.js' %}" crossorigin="anonymous"></script>
</body>

</html>

core/templates/gallery.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="{% static 'css/grid-gallery.css'%}">
    <style>
       #mainNav{
           background-color: #212529 !important;
       }
       #a-gallery {
           background-color: #FFBE00 !important;
           color:black;
       }
      
    
    </style>
    <!-- Heading Row-->
    <header id="galeria" class="heading">
         <div class="container">
            <div class="row">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">GALERIA</h2>
                </div>
            </div>
    </header>
    
    <section class="page-section bg-light gallery-block grid-gallery h-100" id="galeria">
        <div class="container">
            <div class="row">
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/2.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/2.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/3.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/3.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/4.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/4.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/5.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/5.jpeg'%}">
                        </a>
                    </div>  
                    
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/7.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/7.jpeg'%}">
                        </a>
                    </div>  
                   
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/9.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/9.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/10.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/10.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/11.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/11.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/12.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/12.jpeg'%}">
                        </a>
                    </div>  
                    <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/1.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/1.jpeg'%}">
                        </a>
                    </div>
                     <div class="col-md-6 col-lg-4 item">
                        <a class="lightbox" href="{% static 'assets/img/galeria/8.jpeg'%}">
                            <img class="img-fluid image scale-on-hover" src="{% static 'assets/img/galeria/8.jpeg'%}">
                        </a>
                    </div>  

            </div>
        </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.grid-gallery', { animation: 'slideIn'});
    </script>
    
{% endblock %}

core/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <style>
       
    </style>
    <!-- Masthead-->
    <header class="masthead">
        <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel"  data-interval="300" data-pause="false">
               
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'assets/img/destaques/1.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'assets/img/destaques/2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'assets/img/destaques/3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
        </div>
    </header>
    <!-- Faca Parte-->
    <section class="page-section" id="facaparte">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Letras Potengienses</h2>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <h4 class="my-3 step">1</h4>
                    <p>É autor ou leitor e deseja compartilhar suas obras no portal? O portal ajudará a compartilhar e indexar suas obras favoritas.</p>
                </div>
                
                <div class="col-md-4">
                    <h4 class="my-3 step">2</h4>
                    <p> Envie um email para letraspotengienses@gmail.com ou um direct para o instagram @letraspotengienses.</p>
                </div>
                <div class="col-md-4">
                    <h4 class="my-3 step">3</h4>
                    <p>Já entrou em contato? A equipe do projeto responderá seu contato.</p>
                </div>
                
            </div>
        </div>
    </section>
    <!-- Depoimentos-->
    <section class="page-section" id="depoimentos">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Reflexões</h2>
            </div>
            <div class="row text-center">
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel"  data-interval="">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="carousel-caption d-none d-md-block">
                                <p>"A comunicação pela Palavra vocal é uma das experiências mais admiráveis de nossa condição de Ser biológico e espiritual. Através de uma simples vibração sonora captada pelo ouvido do interlocutor, podemos transmitir as ideias mais abstratas e os sentimentos mais sutis. Se a Palavra do Homem tem condição de ser honesta, sincera, leal e verdadeira, imaginemos a Palavra de Deus! Esta que é amparo, proteção, conforto e alegria. Esta que é força e inspiração, luz e elevação, verdade e justiça, firmeza e fecundidade."</p>
                                <small>José Ferreira Rocha</small>
                            </div>
                        </div>
                        
                    </div>  
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>  
                </div>
            </div>   
        </div>
    </section>
{% endblock %}